version: "3.8"

networks:
  web:
   external: true
  internal:
    external: false

services:
  db:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: othersupply
    volumes:
       - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

  api:
    image: kyleconkright/other-supply-api:1.0.0
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - web
      - internal
  
  # client:
  #   image: kyleconkright/other-supply-client:1.0.0
  #   restart: on-failure
  #   build:
  #     context: ./client
  #   ports:
  #     - 3000:3000
  #     - "24678:24678"
  #   volumes:
  #     - ./client:/usr/src/app
  #     - /usr/src/app/node_modules
  #   # networks:
  #   #   - web
  #   #   - internal